## Connector

In [2]:
!pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in C:\Users\rahan\AppData\Local\Programs\Python\Python313\Lib\site-packages (9.5.0)

In [13]:
import mysql.connector

In [4]:
conn = mysql.connector.connect(host = 'localhost', user = 'root', password = 'root123', database = 'batch22')

In [5]:
if conn.is_connected():
    print('successful')

successful

In [6]:
query = 'select * from employee'
import pandas as pd
df = pd.read_sql(query, conn)
df.head()

C:\Users\rahan\AppData\Local\Temp\ipykernel_27012\3476566615.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

,EmployeeID,FirstName,LastName,Department,Position,Salary,HireDate
0,1,John,Doe,HR,HR Manager,60000.0,2015-04-22
1,2,Jane,Smith,IT,Software Engineer,75000.0,2017-08-15
2,3,Michael,Brown,Finance,Accountant,58000.0,2016-03-10
3,4,Emily,Johnson,IT,Data Analyst,72000.0,2019-11-01
4,5,David,Wilson,Marketing,Marketing Manager,68000.0,2014-02-18

In [7]:
import warnings
warnings.filterwarnings('ignore')

In [8]:
type(df)

pandas.DataFrame

In [9]:
%pip install pandas

Requirement already satisfied: pandas in C:\Users\rahan\AppData\Local\Programs\Python\Python313\Lib\site-packages (3.0.5)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\rahan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\rahan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\rahan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in C:\Users\rahan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [17]:
import mysql.connector

In [18]:
con = mysql.connector.connect(host = 'localhost', user= 'root', password = 'root123', database = 'sakila')

In [20]:
if con.is_connected():
    print('Successful')

Successful

In [21]:
query = 'select * from film'
import pandas as pd
data = pd.read_sql(query, con)
data

,film_id,title,description,release_year,language_id,original_language_id,rental_duration,rental_rate,length,replacement_cost,rating,special_features,last_update
0,1,ACADEMY DINOSAUR,A Epic Drama of a Feminist And a Mad Scientist...,2006,1,None,6,0.99,86,20.99,PG,"{Deleted Scenes, Behind the Scenes}",2006-02-15 05:03:42
1,2,ACE GOLDFINGER,A Astounding Epistle of a Database Administrat...,2006,1,None,3,4.99,48,12.99,G,"{Deleted Scenes, Trailers}",2006-02-15 05:03:42
2,3,ADAPTATION HOLES,A Astounding Reflection of a Lumberjack And a ...,2006,1,None,7,2.99,50,18.99,NC-17,"{Deleted Scenes, Trailers}",2006-02-15 05:03:42
3,4,AFFAIR PREJUDICE,A Fanciful Documentary of a Frisbee And a Lumb...,2006,1,None,5,2.99,117,26.99,G,"{Commentaries, Behind the Scenes}",2006-02-15 05:03:42
4,5,AFRICAN EGG,A Fast-Paced Documentary of a Pastry Chef And ...,2006,1,None,6,2.99,130,22.99,G,{Deleted Scenes},2006-02-15 05:03:42
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,YOUNG LANGUAGE,A Unbelieveable Yarn of a Boat And a Database ...,2006,1,None,6,0.99,183,9.99,G,"{Behind the Scenes, Trailers}",2006-02-15 05:03:42
996,997,YOUTH KICK,A Touching Drama of a Teacher And a Cat who mu...,2006,1,None,4,0.99,179,14.99,NC-17,"{Behind the Scenes, Trailers}",2006-02-15 05:03:42
997,998,ZHIVAGO CORE,A Fateful Yarn of a Composer And a Man who mus...,2006,1,None,6,0.99,105,10.99,NC-17,{Deleted Scenes},2006-02-15 05:03:42
998,999,ZOOLANDER FICTION,A Fateful Reflection of a Waitress And a Boat ...,2006,1,None,5,2.99,101,28.99,R,"{Deleted Scenes, Trailers}",2006-02-15 05:03:42
999,1000,ZORRO ARK,A Intrepid Panorama of a Mad Scientist And a B...,2006,1,None,3,4.99,50,18.99,NC-17,"{Commentaries, Behind the Scenes, Trailers}",2006-02-15 05:03:42

In [22]:
data.head()

,film_id,title,description,release_year,language_id,original_language_id,rental_duration,rental_rate,length,replacement_cost,rating,special_features,last_update
0,1,ACADEMY DINOSAUR,A Epic Drama of a Feminist And a Mad Scientist...,2006,1,None,6,0.99,86,20.99,PG,"{Deleted Scenes, Behind the Scenes}",2006-02-15 05:03:42
1,2,ACE GOLDFINGER,A Astounding Epistle of a Database Administrat...,2006,1,None,3,4.99,48,12.99,G,"{Deleted Scenes, Trailers}",2006-02-15 05:03:42
2,3,ADAPTATION HOLES,A Astounding Reflection of a Lumberjack And a ...,2006,1,None,7,2.99,50,18.99,NC-17,"{Deleted Scenes, Trailers}",2006-02-15 05:03:42
3,4,AFFAIR PREJUDICE,A Fanciful Documentary of a Frisbee And a Lumb...,2006,1,None,5,2.99,117,26.99,G,"{Commentaries, Behind the Scenes}",2006-02-15 05:03:42
4,5,AFRICAN EGG,A Fast-Paced Documentary of a Pastry Chef And ...,2006,1,None,6,2.99,130,22.99,G,{Deleted Scenes},2006-02-15 05:03:42

In [23]:
type(con)

mysql.connector.connection_cext.CMySQLConnection

In [24]:
type(data)

pandas.DataFrame

In [25]:
type(conn)

mysql.connector.connection_cext.CMySQLConnection