# Pandas
- Library for data wrangling , cleaning , manipulation
- Intrinsic data alignment done through labeling.
- Functions such as merge, groupby , and join.
- Handle Missing Values.
- Data Standardisation.
- Is built on top of Numpy. 
- Fast and Efficient when it comes to data wrangling.
- Tools for reading and writing data.
- Data aggregation and transformation.

## Data Structures of Pandas
- Series : One dimensional
- Dataframe : Two dimensional

### Series
- One dimensional
- Data and labels. Labels are also called indexes.
- Data alignment is intrinsic and takes place automatically.
- Change the data alignment by indexing.

In [4]:
import pandas as pd

In [5]:
lst = [3,5,7,9,34,71,878]

In [6]:
ser1 = pd.Series(lst)
ser1

0      3
1      5
2      7
3      9
4     34
5     71
6    878
dtype: int64

In [7]:
ser2 = pd.Series(lst, index = ['a','b','c','d','e','f','g'])
ser2

a      3
b      5
c      7
d      9
e     34
f     71
g    878
dtype: int64

In [8]:
# convert tuple into series

In [9]:
# convert dictionary into series
dict1 = {'a' : 10, 'b': 20, 'c' : 30}

In [10]:
ser3 = pd.Series(dict1)
ser3

a    10
b    20
c    30
dtype: int64

In [11]:
# Accessing data into labels
student_marks = pd.Series([99,98,97,96,95], index = ['Maths','Chemistry','English','Physics','Biology'])
student_marks

Maths        99
Chemistry    98
English      97
Physics      96
Biology      95
dtype: int64

In [12]:
print(student_marks['Chemistry'])

98

In [13]:
print(student_marks['Chemistry':'Biology'])

Chemistry    98
English      97
Physics      96
Biology      95
dtype: int64

In [14]:
student_marks['Biology'] = 98
student_marks

Maths        99
Chemistry    98
English      97
Physics      96
Biology      98
dtype: int64

In [15]:
student_marks[1]

C:\Users\rahan\AppData\Local\Temp\ipykernel_2204\2496512771.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  student_marks[1]

np.int64(98)

In [16]:
dir(student_marks)

['Biology',
 'Chemistry',
 'English',
 'Maths',
 'Physics',
 'T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__bool__',
 '__class__',
 '__column_consortium_standard__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__firstlineno__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pandas_priority__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__static_attributes__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_accum_func',
 '_agg_examples_doc',
 '_agg_see_also_doc',
 '_align_for_op',
 '_align_frame',
 '_align_series',
 '_append',
 '_arith_method',
 '_as_manager',
 '_attrs',
 '_binop',
 '_can_hold_na',
 '_check_inplace_and_allows_duplicate_labels',
 '_check_is_chained_assignment_possible',
 '_check_label_or_level_ambiguity',
 '_check_setitem_copy',
 '_clear_item_cache',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_cmp_method',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_result',
 '_constructor',
 '_constructor_expanddim',
 '_constructor_expanddim_from_mgr',
 '_constructor_from_mgr',
 '_data',
 '_deprecate_downcast',
 '_dir_additions',
 '_dir_deletions',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_duplicated',
 '_find_valid_index',
 '_flags',
 '_flex_method',
 '_from_mgr',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cacher',
 '_get_cleaned_column_resolvers',
 '_get_index_resolvers',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_rows_with_mask',
 '_get_value',
 '_get_values_tuple',
 '_get_with',
 '_getitem_slice',
 '_gotitem',
 '_hidden_attrs',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_init_dict',
 '_init_mgr',
 '_inplace_method',
 '_internal_names',
 '_internal_names_set',
 '_is_cached',
 '_is_copy',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_is_view',
 '_is_view_after_cow_rules',
 '_item_cache',
 '_ixs',
 '_logical_func',
 '_logical_method',
 '_map_values',
 '_maybe_update_cacher',
 '_memory_usage',
 '_metadata',
 '_mgr',
 '_min_count_stat_function',
 '_name',
 '_needs_reindex_multi',
 '_pad_or_backfill',
 '_protect_consolidate',
 '_reduce',
 '_references',
 '_reindex_axes',
 '_reindex_indexer',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_rename',
 '_replace_single',
 '_repr_data_resource_',
 '_repr_latex_',
 '_reset_cache',
 '_reset_cacher',
 '_set_as_cached',
 '_set_axis',
 '_set_axis_name',
 '_set_axis_nocheck',
 '_set_is_copy',
 '_set_labels',
 '_set_name',
 '_set_value',
 '_set_values',
 '_set_with',
 '_set_with_engine',
 '_shift_with_freq',
 '_slice',
 '_stat_function',
 '_stat_function_ddof',
 '_take_with_is_copy',
 '_to_latex_via_styler',
 '_typ',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'apply',
 'argmax',
 'argmin',
 'argsort',
 'array',
 'asfreq',
 'asof',
 'astype',
 'at',
 'at_time',
 'attrs',
 'autocorr',
 'axes',
 'backfill',
 'between',
 'between_time',
 'bfill',
 'bool',
 'case_when',
 'clip',
 'combine',
 'combine_first',
 'compare',
 'convert_dtypes',
 'copy',
 'corr',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'div',
 'divide',
 'divmod',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtype',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'ewm',
 'expanding',
 'explode',
 'factorize',
 'ffill',
 'fillna',
 'filter',
 'first',
 'first_valid_index',
 'flags',
 'floordiv',
 'ge',
 'get',
 'groupby',
 'gt',
 'hasnans',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'interpolate',
 'is_monotonic_decreasing',
 'is_monotonic_increasing',
 'is_unique',
 'isin',
 'isna',
 'isnull',
 'item',
 'items',
 'keys',
 'kurt',
 'kurtosis',
 'last',
 'last_valid_index',
 'le',
 'list',
 'loc',
 'lt',
 'map',
 'mask',
 'max',
 'mean',
 'median',
 'memory_usage',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'name',
 'nbytes',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pad',
 'pct_change',
 'pipe',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'radd',
 'rank',
 'ravel',
 'rdiv',
 'rdivmod',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'repeat',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'searchsorted',
 'sem',
 'set_axis',
 'set_flags',
 'shape',
 'shift',
 'size',
 'skew',
 'sort_index',
 'sort_values',
 'squeeze',
 'std',
 'struct',
 'sub',
 'subtract',
 'sum',
 'swapaxes',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_frame',
 'to_hdf',
 'to_json',
 'to_latex',
 'to_list',
 'to_markdown',
 'to_numpy',
 'to_period',
 'to_pickle',
 'to_sql',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tz_convert',
 'tz_localize',
 'unique',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'view',
 'where',
 'xs']

In [17]:
student_marks

Maths        99
Chemistry    98
English      97
Physics      96
Biology      98
dtype: int64

In [18]:
# iloc =  we have to send index address
print(student_marks.iloc[2])

97

In [19]:
# loc =  we have to send label address
print(student_marks.loc['English'])

97

In [20]:
#### Vectorised operations
seriesA = pd.Series([1,2,3,4,5], index = ['a','b','c','d','f'])
seriesB = pd.Series([6,7,8,9,10], index = ['a','b','c','d','f'])

In [21]:
seriesC = seriesA + seriesB
seriesC

a     7
b     9
c    11
d    13
f    15
dtype: int64

In [22]:
# Vetorized Operations
seriesD = pd.Series([1,2,3,4,5], index = ['a','b','c','d','f'])
seriesE = pd.Series([6,7,8,9], index = ['f','a','c','d'])

In [23]:
seriesF = seriesD + seriesE
seriesF

a     8.0
b     NaN
c    11.0
d    13.0
f    11.0
dtype: float64

In [24]:
# handling null value
seriesF.dropna()

a     8.0
c    11.0
d    13.0
f    11.0
dtype: float64

In [25]:
seriesF.fillna(2)

a     8.0
b     2.0
c    11.0
d    13.0
f    11.0
dtype: float64

In [26]:
# mean, median, mode
print(seriesF.mean())

10.75

In [27]:
print(seriesF.median())

11.0

In [28]:
print(seriesF.mode())

0    11.0
dtype: float64

In [29]:
seriesF.fillna(seriesF.mean())

a     8.00
b    10.75
c    11.00
d    13.00
f    11.00
dtype: float64

### Dataframe

- Two Dimensional
- labelled data structures
- column can be used of different datatypes
- looks like a spread-sheet

In [30]:
list1 = [2,3,4,5,6,7]
DF = pd.DataFrame(list1)
DF

   0
0  2
1  3
2  4
3  5
4  6
5  7

In [31]:
DF1 = pd.DataFrame(list1, columns = ['A'])
DF1

   A
0  2
1  3
2  4
3  5
4  6
5  7

In [32]:
DF2 = pd.DataFrame(list1, index = ['a','b','c','d','e','f'], columns = ['A'])
DF2

   A
a  2
b  3
c  4
d  5
e  6
f  7

In [33]:
import numpy as np

In [34]:
# dataframe from numpy array
arr_2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
DF3 = pd.DataFrame(arr_2D)
DF3

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [36]:
DF4 = pd.DataFrame(arr_2D, index = ['A','B','C'],columns = ['a','b','c'])
DF4

   a  b  c
A  1  2  3
B  4  5  6
C  7  8  9

In [37]:
print(DF4.columns)

Index(['a', 'b', 'c'], dtype='object')

In [38]:
print(DF4.index)

Index(['A', 'B', 'C'], dtype='object')

In [39]:
#1
l1 = [10,20,30,40]
N1 = np.array(l1)
S1 = pd.Series(N1)
S1

0    10
1    20
2    30
3    40
dtype: int64

In [40]:
#2
S2 = pd.Series(N1, index = ['a','b','c','d'])
print(S2)
print(S2.iloc[3])
print(S2.loc['c'])

a    10
b    20
c    30
d    40
dtype: int64
40
30

In [43]:
#3
S2['d'] = 50
print(S2)

a    10
b    20
c    30
d    50
dtype: int64

In [44]:
#4
N2 = {'A' : 1, 'B' : 2, 'C' : 3}
S3 = pd.Series(N2)
print(S3)

A    1
B    2
C    3
dtype: int64

In [45]:
#5
S3.index = ['X','Y','Z']
print(S3)

X    1
Y    2
Z    3
dtype: int64

In [46]:
#6
print(S3.iloc[0])
print(S3.iloc[1])
print('---------------------------')
S4 = pd.Series([1,8,9,21,35], index = ['a','b','c','d','e'])
S5 = pd.Series([2,7,7,23,41], index = ['d','b','e','a','c'])
S6 = S4 + S5
print(S6)
print('---------------------------')
S7 = S4 * 5 
print(S7)

1
2
---------------------------
a    24
b    15
c    50
d    23
e    42
dtype: int64
---------------------------
a      5
b     40
c     45
d    105
e    175
dtype: int64

In [47]:
# Create a data frame using series
count = pd.Series([205, 204, 201, 200,197], index = [2012, 2008,  2004, 2000, 1996])
host_city = pd.Series(['London', 'Beijing', 'Athens', 'Sydney', ' Atlanta'], index = [2012, 2008,  2004, 2000, 1996])

In [48]:
DF22 = pd.DataFrame({'Count' : count, 'City' : host_city})
DF22

      Count      City
2012    205    London
2008    204   Beijing
2004    201    Athens
2000    200    Sydney
1996    197   Atlanta

In [51]:
DF22['Count']

2012    205
2008    204
2004    201
2000    200
1996    197
Name: Count, dtype: int64

In [52]:
DF22['City']

2012      London
2008     Beijing
2004      Athens
2000      Sydney
1996     Atlanta
Name: City, dtype: object

In [53]:
# loc and iloc in dataframe

DF22.iloc[2]

Count       201
City     Athens
Name: 2004, dtype: object

In [54]:
DF22.loc[2008]

Count        204
City     Beijing
Name: 2008, dtype: object

### groupby

In [55]:
df_name = pd.DataFrame({'first':['George','Bill','Ronald','Jimmy','George'],
                        'second':['Bush','Clinton','Reagan','Carter','Washington'],
                       'score':[3,1,2,1,1]})
df_name

    first      second  score
0  George        Bush      3
1    Bill     Clinton      1
2  Ronald      Reagan      2
3   Jimmy      Carter      1
4  George  Washington      1

In [57]:
g = df_name.groupby('first')
g.size() # to know the size of groupby columns how many times comes.

first
Bill      1
George    2
Jimmy     1
Ronald    1
dtype: int64

In [60]:
g.get_group('George') # get_group is used to find group of particular data in dataframe.

    first      second  score
0  George        Bush      3
4  George  Washington      1

In [61]:
df_name

    first      second  score
0  George        Bush      3
1    Bill     Clinton      1
2  Ronald      Reagan      2
3   Jimmy      Carter      1
4  George  Washington      1

In [62]:
type(df_name)

pandas.core.frame.DataFrame

In [67]:
df_name.info() # info() give complete information of dataframe.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   first   5 non-null      object
 1   second  5 non-null      object
 2   score   5 non-null      int64
dtypes: int64(1), object(2)
memory usage: 252.0+ bytes

In [70]:
df_name.describe() # dercribe() works as to find statistical values of present dataframe.

          score
count  5.000000
mean   1.600000
std    0.894427
min    1.000000
25%    1.000000
50%    1.000000
75%    2.000000
max    3.000000

In [2]:
import pandas as pd
Data = pd.read_csv("User_Data.csv")

In [3]:
Data

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [4]:
Data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   User ID          400 non-null    int64
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64
 3   EstimatedSalary  400 non-null    int64
 4   Purchased        400 non-null    int64
dtypes: int64(4), object(1)
memory usage: 15.8+ KB

In [5]:
Data.describe()

            User ID         Age  EstimatedSalary   Purchased
count  4.000000e+02  400.000000       400.000000  400.000000
mean   1.569154e+07   37.655000     69742.500000    0.357500
std    7.165832e+04   10.482877     34096.960282    0.479864
min    1.556669e+07   18.000000     15000.000000    0.000000
25%    1.562676e+07   29.750000     43000.000000    0.000000
50%    1.569434e+07   37.000000     70000.000000    0.000000
75%    1.575036e+07   46.000000     88000.000000    1.000000
max    1.581524e+07   60.000000    150000.000000    1.000000

In [9]:
Data.head(7)

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0
5  15728773    Male   27            58000          0
6  15598044  Female   27            84000          0

In [8]:
Data.tail(9)

      User ID  Gender  Age  EstimatedSalary  Purchased
391  15592570    Male   47            23000          1
392  15748589  Female   45            45000          1
393  15635893    Male   60            42000          1
394  15757632  Female   39            59000          0
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

In [10]:
Data.tail()

      User ID  Gender  Age  EstimatedSalary  Purchased
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

In [11]:
Data.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [16]:
Data.iloc[345:356]

      User ID  Gender  Age  EstimatedSalary  Purchased
345  15716781  Female   41            63000          0
346  15646936    Male   53            72000          1
347  15768151  Female   54           108000          1
348  15579212    Male   39            77000          0
349  15721835    Male   38            61000          0
350  15800515  Female   38           113000          1
351  15591279    Male   37            75000          0
352  15587419  Female   42            90000          1
353  15750335  Female   37            57000          0
354  15699619    Male   36            99000          1
355  15606472    Male   60            34000          1

In [21]:
Data.loc[245:254]

      User ID  Gender  Age  EstimatedSalary  Purchased
245  15722061  Female   51           146000          1
246  15638003  Female   35            50000          0
247  15775590  Female   57           122000          1
248  15730688    Male   41            52000          0
249  15753102  Female   35            97000          1
250  15810075  Female   44            39000          0
251  15723373    Male   37            52000          0
252  15795298  Female   48           134000          1
253  15584320  Female   37           146000          1
254  15724161  Female   50            44000          0